from __future__ import annotations

import hashlib
import json
import subprocess
import sys
import zipfile
from pathlib import Path

import pytest
import yaml

from scripts.check_release_hygiene import (
    _credential_findings,
    _notebook_text,
    _path_findings,
    _text_findings,
    scan_asset_directory,
    scan_commit_messages,
    scan_github_event,
    scan_release_json,
    scan_repository,
    scan_text_file,
)


def _release_contract(version: str, tag_message: str) -> dict[str, object]:
    return {
        "release_version": version,
        "release_ref": f"v{version}",
        "history_policy": {"tag_message": tag_message},
    }


def _assistant_product() -> str:
    return "Chat" + "GPT"


def _fake_openai_token() -> str:
    return "sk-" + "proj-" + "abcdefghijklmnopqrstuvwxyz012345"


def _write_asset_checksums(asset_dir: Path, relative_paths: set[str]) -> None:
    lines = []
    for relative in sorted(relative_paths - {"SHA256SUMS"}):
        digest = hashlib.sha256((asset_dir / relative).read_bytes()).hexdigest()
        lines.append(f"{digest}  {relative}")
    (asset_dir / "SHA256SUMS").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _initialize_tagged_release(repository: Path) -> tuple[str, str]:
    tag_message = "Reproducibility and metadata maintenance release"
    notes = "Reviewed release notes.\n"
    subprocess.run(["git", "init", "-q"], cwd=repository, check=True)
    subprocess.run(["git", "config", "user.name", "Release Test"], cwd=repository, check=True)
    subprocess.run(["git", "config", "user.email", "release@example.invalid"], cwd=repository, check=True)
    (repository / "RELEASE_NOTES_v1.1.0.md").write_text(notes, encoding="utf-8")
    subprocess.run(["git", "add", "RELEASE_NOTES_v1.1.0.md"], cwd=repository, check=True)
    subprocess.run(["git", "commit", "-qm", "Release candidate"], cwd=repository, check=True)
    subprocess.run(["git", "tag", "-a", "v1.1.0", "-m", tag_message], cwd=repository, check=True)
    return tag_message, notes


def test_hygiene_rejects_process_residue() -> None:
    findings = _text_findings(
        "README.md",
        "Prepared by " + _assistant_product() + "\nresponse-" + "ready table\n",
    )
    reasons = {finding.reason for finding in findings}
    assert "assistant product name" in reasons
    assert "AI authorship claim" in reasons
    assert "response scaffolding" in reasons


def test_hygiene_rejects_broader_authorship_claims() -> None:
    examples = (
        "AI-" + "prepared repository",
        "Repository created with " + "AI assistance",
        "Produced by an " + "AI system",
        "Documentation prepared using " + "AI",
        "Release written with " + "OpenAI",
        "Code generated using " + "GPT-5",
        "This README was prepared with " + "GPT-5",
        "GPT-5-" + "prepared repository",
        "OpenAI-" + "written documentation",
        "Documentation prepared with assistance from " + "OpenAI",
        "Repository prepared with the help of " + "GPT-5",
        "OpenAI assisted with " + "preparing this repository",
        "Documentation was prepared\n" + "using GPT-5",
    )
    for example in examples:
        reasons = {finding.reason for finding in _text_findings("README.md", example)}
        assert "AI authorship claim" in reasons


def test_hygiene_allows_scientific_llm_language() -> None:
    findings = _text_findings(
        "README.md",
        "Large language models generated diagnostic likelihood-ratio outputs using the OpenAI API.\n"
        "Likelihood-ratio outputs were generated by GPT-5.",
    )
    assert findings == []


def test_hygiene_rejects_credentials() -> None:
    findings = _text_findings("notebook.md", _fake_openai_token())
    assert {finding.reason for finding in findings} == {"OpenAI credential pattern"}


def test_hygiene_allows_frozen_threshold_filename() -> None:
    path = "data/model_outputs/threshold_perturbation_v1/threshold_perturbation_reviewer_table.csv"
    assert _path_findings(path) == []


def test_hygiene_allows_only_exact_root_agents_file() -> None:
    assert _path_findings("AGENTS.md") == []
    for path in ("agents.md", "docs/AGENTS.md", "nested/agents.md"):
        reasons = {finding.reason for finding in _path_findings(path)}
        assert "only the reviewed root AGENTS.md is allowed" in reasons


def test_hygiene_rejects_private_and_temporary_paths() -> None:
    paths = (
        "private-draft.md",
        "reviewer-response.md",
        "temporary-output.csv",
        "old-manuscript.md",
        "notes/" + "scr" + "atch_notes.md",
    )
    for path in paths:
        assert _path_findings(path), path


def test_hygiene_scans_inline_notebook_comments() -> None:
    marker = "scr" + "atch marker"
    notebook = '{"cells":[{"cell_type":"code","source":["x = 1  # ' + marker + '"]}]}'
    extracted = _notebook_text(notebook, "analysis.ipynb")
    assert marker in extracted
    assert {finding.reason for finding in _text_findings("analysis.ipynb", extracted)} == {
        "repository-generation scaffold"
    }


def test_hygiene_scans_complete_notebook_source_for_credentials() -> None:
    notebook = json.dumps(
        {"cells": [{"cell_type": "code", "source": ["key = " + repr(_fake_openai_token())]}]}
    )
    assert {finding.reason for finding in _credential_findings("analysis.ipynb", notebook)} == {
        "OpenAI credential pattern"
    }


def test_hygiene_scans_external_publication_text(tmp_path: Path) -> None:
    body = tmp_path / "pr-body.md"
    body.write_text("Prepared by an " + "AI system\n", encoding="utf-8")
    assert {finding.reason for finding in scan_text_file(body, "pull-request-body")} == {"AI authorship claim"}


def test_hygiene_scans_pull_request_event_text(tmp_path: Path) -> None:
    event = tmp_path / "event.json"
    event.write_text(
        '{"pull_request":{"title":"Documentation update","body":"Produced by an ' + 'AI system"}}',
        encoding="utf-8",
    )
    assert {finding.reason for finding in scan_github_event(event)} == {"AI authorship claim"}


def test_hygiene_without_origin_main_scans_only_current_commit(tmp_path: Path) -> None:
    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    subprocess.run(["git", "config", "user.name", "Release Test"], cwd=tmp_path, check=True)
    subprocess.run(["git", "config", "user.email", "release@example.invalid"], cwd=tmp_path, check=True)
    tracked = tmp_path / "file.txt"
    tracked.write_text("one\n", encoding="utf-8")
    subprocess.run(["git", "add", "file.txt"], cwd=tmp_path, check=True)
    subprocess.run(["git", "commit", "-qm", "Prepared by " + _assistant_product()], cwd=tmp_path, check=True)
    tracked.write_text("two\n", encoding="utf-8")
    subprocess.run(["git", "commit", "-qam", "Prepare release tree"], cwd=tmp_path, check=True)
    assert scan_commit_messages(tmp_path) == []


def test_hygiene_scans_current_commit_when_origin_main_equals_head(tmp_path: Path) -> None:
    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    subprocess.run(["git", "config", "user.name", "Release Test"], cwd=tmp_path, check=True)
    subprocess.run(["git", "config", "user.email", "release@example.invalid"], cwd=tmp_path, check=True)
    (tmp_path / "file.txt").write_text("one\n", encoding="utf-8")
    subprocess.run(["git", "add", "file.txt"], cwd=tmp_path, check=True)
    subprocess.run(["git", "commit", "-qm", "Prepared by " + _assistant_product()], cwd=tmp_path, check=True)
    subprocess.run(["git", "update-ref", "refs/remotes/origin/main", "HEAD"], cwd=tmp_path, check=True)

    reasons = {finding.reason for finding in scan_commit_messages(tmp_path)}
    assert "assistant product name" in reasons
    assert "AI authorship claim" in reasons

    missing_base_reasons = {
        finding.reason
        for finding in scan_commit_messages(tmp_path, base_commit="f" * 40, head_commit="HEAD")
    }
    assert "AI authorship claim" in missing_base_reasons


def test_hygiene_scans_all_commits_on_divergent_head(tmp_path: Path) -> None:
    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    subprocess.run(["git", "config", "user.name", "Release Test"], cwd=tmp_path, check=True)
    subprocess.run(["git", "config", "user.email", "release@example.invalid"], cwd=tmp_path, check=True)
    tracked = tmp_path / "file.txt"
    tracked.write_text("legacy\n", encoding="utf-8")
    subprocess.run(["git", "add", "file.txt"], cwd=tmp_path, check=True)
    subprocess.run(["git", "commit", "-qm", "Legacy main"], cwd=tmp_path, check=True)
    subprocess.run(["git", "update-ref", "refs/remotes/origin/main", "HEAD"], cwd=tmp_path, check=True)

    subprocess.run(["git", "switch", "--orphan", "release-root"], cwd=tmp_path, check=True, capture_output=True)
    tracked.write_text("root\n", encoding="utf-8")
    subprocess.run(["git", "add", "file.txt"], cwd=tmp_path, check=True)
    subprocess.run(["git", "commit", "-qm", "Prepared by " + _assistant_product()], cwd=tmp_path, check=True)
    tracked.write_text("head\n", encoding="utf-8")
    subprocess.run(["git", "commit", "-qam", "Finalize release tree"], cwd=tmp_path, check=True)

    reasons = {finding.reason for finding in scan_commit_messages(tmp_path)}
    assert "AI authorship claim" in reasons


def test_hygiene_has_no_whole_file_credential_exemption(tmp_path: Path) -> None:
    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    target = tmp_path / "scripts" / "check_release_hygiene.py"
    target.parent.mkdir()
    target.write_text("token = " + repr(_fake_openai_token()) + "\n", encoding="utf-8")
    subprocess.run(["git", "add", "."], cwd=tmp_path, check=True)

    reasons = {finding.reason for finding in scan_repository(tmp_path)}
    assert "OpenAI credential pattern" in reasons


def test_hygiene_verifies_exact_release_json(tmp_path: Path) -> None:
    notes = "Reviewed release notes.\n"
    contract = _release_contract("1.1.0", "Reproducibility and metadata maintenance release")
    (tmp_path / "RELEASE_NOTES_v1.1.0.md").write_text(notes, encoding="utf-8")
    release = tmp_path / "release.json"
    release.write_text(
        '{"name":"v1.1.0 — Reproducibility and metadata maintenance release",'
        '"body":"Reviewed release notes.\\n"}',
        encoding="utf-8",
    )
    assert scan_release_json(release, tmp_path, contract) == []

    release.write_text(
        '{"release":{"name":"v1.1.0 — Reproducibility and metadata maintenance release",'
        '"body":"Reviewed release notes.\\n"}}',
        encoding="utf-8",
    )
    assert scan_release_json(release, tmp_path, contract) == []

    release.write_text(
        '{"name":"v1.1.0 — Reproducibility and metadata maintenance release","body":"Prepared by an '
        + 'AI system"}',
        encoding="utf-8",
    )
    reasons = {finding.reason for finding in scan_release_json(release, tmp_path, contract)}
    assert "release body differs from RELEASE_NOTES_v1.1.0.md" in reasons
    assert "AI authorship claim" in reasons


def test_hygiene_derives_exact_release_text_from_checked_out_annotated_tag(tmp_path: Path) -> None:
    tag_message, notes = _initialize_tagged_release(tmp_path)
    release = tmp_path / "release.json"
    release.write_text(
        json.dumps(
            {
                "release": {
                    "tag_name": "v1.1.0",
                    "name": f"v1.1.0 — {tag_message}",
                    "body": notes,
                }
            }
        ),
        encoding="utf-8",
    )

    assert scan_release_json(release, tmp_path) == []

    release.write_text(
        json.dumps(
            {
                "release": {
                    "tag_name": "v1.1.0",
                    "name": "v1.1.0 — Changed title",
                    "body": "Changed release notes.\n",
                }
            }
        ),
        encoding="utf-8",
    )
    reasons = {finding.reason for finding in scan_release_json(release, tmp_path)}
    assert "release title differs from the reviewed title" in reasons
    assert "release body differs from RELEASE_NOTES_v1.1.0.md" in reasons


def test_release_event_cli_verifies_exact_tag_derived_text_without_contract(tmp_path: Path) -> None:
    tag_message, notes = _initialize_tagged_release(tmp_path)
    release = tmp_path / "release.json"
    release.write_text(
        json.dumps(
            {
                "release": {
                    "tag_name": "v1.1.0",
                    "name": f"v1.1.0 — {tag_message}",
                    "body": notes,
                }
            }
        ),
        encoding="utf-8",
    )
    script = Path(__file__).resolve().parents[1] / "scripts" / "check_release_hygiene.py"

    result = subprocess.run(
        [
            sys.executable,
            str(script),
            "--repository",
            str(tmp_path),
            "--head-commit",
            "HEAD",
            "--github-event",
            str(release),
            "--release-json",
            str(release),
        ],
        check=False,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, result.stderr
    assert "Release hygiene check passed." in result.stdout


def test_hygiene_requires_release_event_tag_to_match_annotated_head(tmp_path: Path) -> None:
    tag_message, notes = _initialize_tagged_release(tmp_path)
    (tmp_path / "next.txt").write_text("next\n", encoding="utf-8")
    subprocess.run(["git", "add", "next.txt"], cwd=tmp_path, check=True)
    subprocess.run(["git", "commit", "-qm", "Later commit"], cwd=tmp_path, check=True)
    release = tmp_path / "release.json"
    release.write_text(
        json.dumps(
            {
                "release": {
                    "tag_name": "v1.1.0",
                    "name": f"v1.1.0 — {tag_message}",
                    "body": notes,
                }
            }
        ),
        encoding="utf-8",
    )

    reasons = {finding.reason for finding in scan_release_json(release, tmp_path)}
    assert "release tag does not match checked-out HEAD" in reasons


def test_hygiene_derives_exact_asset_inventory_from_contract_version(tmp_path: Path) -> None:
    contract = _release_contract("1.1.0", "Reproducibility and metadata maintenance release")
    expected = {
        "SHA256SUMS",
        "llm-estimate-lrs-v1.1.0.zip",
        "notebooks/data_analysis.executed.ipynb",
        "notebooks/supplementary_analyses.executed.ipynb",
        "reference-tables-v1.1.0.zip",
        "release-attestation.json",
        "validation-report.json",
    }
    for relative in expected:
        path = tmp_path / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.suffix == ".zip":
            with zipfile.ZipFile(path, "w"):
                pass
        else:
            path.write_text("{}\n", encoding="utf-8")
    _write_asset_checksums(tmp_path, expected)

    assert scan_asset_directory(tmp_path, contract) == []
    (tmp_path / "reference-tables-v1.1.0.zip").unlink()
    reasons = {finding.reason for finding in scan_asset_directory(tmp_path, contract)}
    assert "expected release asset is missing" in reasons


@pytest.mark.parametrize(
    ("mutation", "expected_reason"),
    [
        ("changed_asset", "release asset checksum mismatch"),
        ("missing_entry", "asset checksum manifest is missing entries"),
        ("extra_entry", "asset checksum manifest has unexpected entries"),
    ],
)
def test_hygiene_rejects_invalid_asset_checksum_manifest(
    tmp_path: Path,
    mutation: str,
    expected_reason: str,
) -> None:
    contract = _release_contract("1.1.0", "Reproducibility and metadata maintenance release")
    expected = {
        "SHA256SUMS",
        "llm-estimate-lrs-v1.1.0.zip",
        "notebooks/data_analysis.executed.ipynb",
        "notebooks/supplementary_analyses.executed.ipynb",
        "reference-tables-v1.1.0.zip",
        "release-attestation.json",
        "validation-report.json",
    }
    for relative in expected - {"SHA256SUMS"}:
        path = tmp_path / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.suffix == ".zip":
            with zipfile.ZipFile(path, "w"):
                pass
        else:
            path.write_text("{}\n", encoding="utf-8")
    _write_asset_checksums(tmp_path, expected)

    manifest = tmp_path / "SHA256SUMS"
    if mutation == "changed_asset":
        (tmp_path / "validation-report.json").write_text('{"changed": true}\n', encoding="utf-8")
    elif mutation == "missing_entry":
        retained = [
            line
            for line in manifest.read_text(encoding="utf-8").splitlines()
            if not line.endswith("  validation-report.json")
        ]
        manifest.write_text("\n".join(retained) + "\n", encoding="utf-8")
    else:
        manifest.write_text(
            manifest.read_text(encoding="utf-8") + f"{'0' * 64}  unexpected.txt\n",
            encoding="utf-8",
        )

    reasons = {finding.reason for finding in scan_asset_directory(tmp_path, contract)}
    assert any(reason.startswith(expected_reason) for reason in reasons)


def test_current_release_tree_passes_hygiene() -> None:
    repository = Path(__file__).resolve().parents[1]
    assert scan_repository(repository) == []


def test_pull_request_hygiene_reruns_when_editable_text_changes() -> None:
    repository = Path(__file__).resolve().parents[1]
    workflow = yaml.load(
        (repository / ".github/workflows/ci.yml").read_text(encoding="utf-8"),
        Loader=yaml.BaseLoader,
    )
    event_types = set(workflow["on"]["pull_request"]["types"])
    assert {"opened", "synchronize", "reopened", "edited", "ready_for_review"} <= event_types


def test_ci_integrity_lane_runs_smoke_contract() -> None:
    repository = Path(__file__).resolve().parents[1]
    workflow = yaml.load(
        (repository / ".github/workflows/ci.yml").read_text(encoding="utf-8"),
        Loader=yaml.BaseLoader,
    )
    commands = {
        step["run"]
        for step in workflow["jobs"]["unit-and-integrity"]["steps"]
        if isinstance(step, dict) and "run" in step
    }
    assert "make smoke" in commands


def test_published_release_workflow_checks_exact_tag_derived_text() -> None:
    repository = Path(__file__).resolve().parents[1]
    workflow = yaml.load(
        (repository / ".github/workflows/release-hygiene.yml").read_text(encoding="utf-8"),
        Loader=yaml.BaseLoader,
    )
    assert set(workflow["on"]["release"]["types"]) == {"published", "edited"}
    commands = [
        step["run"]
        for step in workflow["jobs"]["release-text"]["steps"]
        if isinstance(step, dict) and "run" in step
    ]
    assert len(commands) == 1
    assert '--github-event "$GITHUB_EVENT_PATH"' in commands[0]
    assert '--release-json "$GITHUB_EVENT_PATH"' in commands[0]
    assert "--contract" not in commands[0]
